### PR TITLE
26049

### PR DESCRIPTION
**Pull request by emoon**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This has two commits, did you intend for that to happen?

**Comment by emoon** [comment]
It's kinda weird because if you look here

https://github.com/emoon/glacier/commit/39b482ae3b58b7a23fd547570c1843577c437581

Github seems to have "merged" all the PRs which I did in a short while (even if they were done on separate branches)

**Comment by steveklabnik** [comment]
What's really strange is that you'd think that because d545d52 was in master, it wouldn't show it... Let' s merge this one and see what happens.

**Comment by steveklabnik** [comment]
Okay, so it's looking like it's still doing the right thing here, so I'll just merge them. Still not sure why it's being weird.

**Pull request merged**
