### PR TITLE
26989

### PR DESCRIPTION
**Pull request by emoon**

### CODE REVIEW

**Comment by steveklabnik** [comment]
@emoon can you maybe share the git commands you're using to make these PRs? I have a hunch...

**Comment by emoon** [comment]
I think I know what the problem is.

When I created a new branch for each PR I did it by doing:

git checkout -b <branch>
.. do stuff, PR, etc
git checkout -b <branch>

Instead of going back to master as base and branch from there.

**Comment by steveklabnik** [comment]
Ah ha! :) 

Too bad that wasn't easier to figure out from GitHub's interface.

**Comment by emoon** [comment]
Yeah. Sorry about that, now the history looks like spagetti :)

history

I will make sure to switch to master before doing any more PRs so lesson learned but yes it would have been nice if the GitHub interface would have hinted about it.

**Pull request merged**
