### PR TITLE
ICE 28189

### PR DESCRIPTION
**Pull request by emoon**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Ah ha! our first success! Travis failed because this has been fixed in the meantime.

So that you get credit, I'm going to merge this anyway, and then remove it in another commit. Thanks so much! :confetti_ball: :tada: :100:

**Comment by emoon** [comment]
Ah!

I was wondering why it was actually failing travis but I got the ICE locally but then it makes sense :)

**Comment by zazdxscf** [comment]
But wait aren't you going to keep it in a separate category called regressions(which are supposed to never fail) ? What if it comes back? :)

**Comment by steveklabnik** [comment]
That's why the tracking bug is moved to E-needs test. That is what should keep it from coming back, the bug isn't fixed until there's a regression test in place.

Though a category might be fun...

**Comment by zazdxscf** [comment]
Got it.
But I mean, you could make another dir into which you just move the ones that pass, and test.sh will (also) fail if any of those fail, this way work is not lost is commit history. Or something like that.

**Pull request merged**
