### PR TITLE
Add test files for several btwn 22354 and 22919

### PR DESCRIPTION
**Pull request by rgardner**
The following tests in this range were not added: 22354, 22387,
22465, 22713, 22781, 22872, 22874. Where possible, the tests come
from the shortest possible code samples to reproduce the ICE.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you so much!

**Comment by wheals** [comment]
It looks like the ones that got checked off on the tracking issue were the ones listed here as not added, and vice versa?

**Comment by rgardner** [comment]
Happy to! I definitely want to take a look at some of the trickier ones (e.x. rust-lang/rust#22354) that will take some more time to understand what's going on from the submitted code sample.

@steveklabnik: this PR added tests for 22565, 22566, 22603, 22789, 22894, and 22919. Sorry for the confusion.

**Comment by steveklabnik** [comment]
Oh! I mis-read, darn. Thanks @wheals , I'll fix it.

**Pull request merged**
